name: pytest

on:
  push:

jobs:
  flake8-pytest:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]
        poetry-version: [1.2.1]
        # os: [ubuntu-18.04, macos-latest, windows-latest]
        os: [ubuntu-18.04, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Pre-install fastext for Windows
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            poetry run pip install https://github.com/ffreemt/ezbee/raw/main/data/artifects/fasttext-0.9.2-cp38-cp38-win_amd64.whl
            poetry run pip install https://github.com/ffreemt/ezbee/raw/main/data/artifects/pycld2-0.41-cp38-cp38-win_amd64.whl
            poetry run pip install https://github.com/ffreemt/ezbee/raw/main/data/artifects/PyICU-2.8.1-cp38-cp38-win_amd64.whl
          else
            poetry run pip install fasttext pycld2 pyicu
          fi
          poetry run pip install https://github.com/ffreemt/ezbee/raw/main/data/artifects/polyglot-16.7.4.tar.gz
        shell: bash
      - name: Install packages
        if: matrix.os == 'windows-latest'
        run: poetry install  # --no-dev
      - name: Run flake8
        run: |
          poetry run flake8 --exit-zero
          # poetry run pytest
      - name: Run pytest
        run: poetry run pytest tests
